### ISSUE TITLE
Request for refresh button

### ISSUE THREAD

**Issue by jkjustjoshing** [filso/ng-dependency-graph#13]
Awesome extension! Thanks!

When I'm actively developing an app and I change a module name or add a module, there's no way to force a refresh of the graph. A refresh button to re-generate everything would be good.

**Comment by filso** [comment]
Thanks a lot!

It should refresh the graph every time the window that it is attached to is refreshed. It assumes that in your workflow after you do any changes to the app, one way or another you would refresh the window.

Is that the case with your app, or maybe you're using some sorts of hot JavaScript code swapping?

**Comment by filso** [comment]
Alright, please give me a shout if it's a bug after all! :) closing it for now
