### ISSUE TITLE
Detect Cyclic Dependencies

### ISSUE THREAD

**Issue by 6220119** [filso/ng-dependency-graph#14]
Could you make it a new feature? :)
It will be helpful to detect smell code, especially when working with legacy code.

**Comment by filso** [comment]
hi 6220119, thank you for feedback.
Plugin scans a graph of a running app, and it depends on runtime data. If you have a cyclic dependency in your app, it won't run. :)

Let me know if that's not what you mean, thanks

**Comment by filso** [comment]
It's a bad idea to scan code from this plugin, that just wouldn't work reliably. To name a few reasons:
accessing full code by browser, various build processes - minification, WebPack etc. all can get in the way, and who's not using them these days?, speed - scanning and analysing code can be very slow, lazy loading - if we scan code, no way to tell if there's more coming

**Comment by filso** [comment]
Better place to do that would be some build script ie. gulp but I don't see how this could work reliably :) as angular allows you to inject dependencies dynamically

**Comment by 6220119** [comment]
Hi filso,

Due to the flexiblness of Angular, we may create hidden circular dependencies, for example:
Ideally, we have 3 separate modules with 3 separate services:
[serviceA] -> [moduleA]
[serviceB] -> [moduleB]
[serviceC] -> [moduleC]

However, in code details, one can write:
[serviceA] -> [serviceB]
[serviceB] -> [serviceC]
[serviceC] -> [serviceA]

Angular will not yell if all three modules are included, we need to detect these *hidden* bad dependencies. In the example, it is just service, but it can be anything...

**Comment by filso** [comment]
It will yell if you try to include any of dependencies from cycle

I don't see though how this is relevant to our discussion. My point is - there's no way to reliably check cycles, and even if there was, this plugin isn't the right place to do that

**Comment by 6220119** [comment]
I rechecked the source code and updated the jsfiddle. Now it won't yell even if used. See https://jsfiddle.net/hbueox41/
To be correct, they are hidden circular module dependencies. Angular will only detect the case where "one service depends on itself"

You are right that this can also be detected at the build step. 
However, I just think that it will be less work to use this plugin to detect circular module dependencies at runtime. Since you have already touched the internal and built the graph structure for the modules already.

I'm afraid that I do not understand clearly what you mean when mentioning about reliability though.
It is true that we have build process, webpack and stuff get in the way but if the circular module dependencies stil escapes them all, then I would be happy to have a browser plugin as a final guard to detect it at runtime, as you said, it is accurate and more straightforward :-)

**Comment by filso** [comment]
@6220119 As for this plugin, it's not that it would be 'more work' to detect it on runtime. It's impossible to detect this on runtime, because nothing will be run. :) Angular won't bootstrap app with cyclic dependencies.

Sorry, but I have a feeling you don't understand what you're talking about :) maybe you could take a look at the injection code, app/scripts/inject/inject.js?

**Comment by 6220119** [comment]
>> because if there are cycles - nothing will be run
This is not correct, please take a look at the example I posted, I made 2 modules depends on each other and the Angular app is still runnable.

>> Sorry, but I have a feeling you don't understand what you're talking about :) maybe you could take a look at the injection code, app/scripts/inject/inject.js?
I also thought that you didn't understand what I meant, so I picked your module detection code and customized for my own need, will public it when I have time to make it look organized :-)

**Comment by filso** [comment]
It's runnable because there's no cycle in component dependencies.

Your example shows module codependency, not component codependency. I don't see what's wrong with it, why would anyone want to detect it? You could argue that it's a bad architecture, but that's another story. It's just some pattern of inversion of control

If there are cycles in a dependency graph of components, the app won't run.

**Comment by 6220119** [comment]
> If there are cycles in a dependency graph of components, the app won't run.

Yes, I get it.

> Your example shows module codependency, not component codependency. I don't see what's wrong with it, so why would anyone want to detect it? You could argue that it's a bad architecture, but that's another story. It's just some pattern of inversion of control

Ok, fine. It is just my principle that allowing "circular module dependencies" is bad as I don't see any use for it other than reducing reusability.

The story behind this is that our team is trying to migrate a legacy angular 1 web application to Angular2. The codebase is full of "circular module dependencies" and this makes upgrading to Angular2 hard. So it would be handy to have a tool to check where to cut off these circular modules and which component should belong to which module.
Your extension has been helpful to help us see how big is this web app, so I just wish to have one more little feature. It doesn't have to be aggressive about this, I would be happy to see these "circular module dependencies" as a warning, just like Chrome's DevTool Audit would do.

So it is fine to close this issue as I don't see how our discussion is going to proceed further.

**Comment by filso** [comment]
Well, if that's what you want to do, then this info could be inferred from runtime data, not necessarily source. :) But this seems a too narrow case to deal with it explicitly. It's hard for me to imagine that would be a common problem when porting apps from Angular 1 -> 2, as you mentioned it's a weird architecture. And even if it is, I guess you can just follow Angular 2 error messages as quickly as this plugin's warnings?

I think that good plugins / apps do a very specific thing, and when they try to do everything and include all features that might be used by say 2% of power users, it mostly adds to the noise and the overall quality drops. So I'm sorry, but I'd rather not make this another feature, I think it's not worth increasing the complexity.

Thanks a lot for the feedback and discussion, very appreciated! If there's ever some hints interface, this could be included, but then again I don't see much use for hints interface (what would we hint? if it's showing data, then the graph is correct). If you have some ideas, then I'll be very happy to be proved wrong :) and create something useful.

BTW I wrote a simple dependency linter some time ago (currently it only checks if injected dependency is used), but it never got it production-ready: https://github.com/filso/ng-dependency-lint
