### ISSUE TITLE
Manual Bootstrapped apps won't load dependencies

### ISSUE THREAD

**Issue by RobHarrisAZ** [filso/ng-dependency-graph#2]
When using the addin on a manually bootstrapped Angular app like so:
    angular.element(document).ready(function () {
        angular.bootstrap(document, ['myApplication']);
    });

The addin can't seem to find the root of the app so it tries to load 'app' as a module which doesn't exist in my app.  This results in an error being thrown from trying to load a module that doesn't exist.

Hopefully you can support this scenario, I was looking forward to using it.

**Comment by Skinner927** [comment]
+1

I'd also like to note there doesn't seem to be a way to turn the plugin off so an error is raised on my page now forever. I unfortunately have to disable the plugin because of it. Perhaps I should create a feature request issue about this.

**Comment by himdel** [comment]
Also +1, but it seems like the only thing needed to stop the error is to remove the [else part](https://github.com/filso/ng-dependency-graph/blob/9260fe3ca960a1c05410f2fe6b9260d104d1930b/app/scripts/inject/debug.js#L163-166).

**Comment by jvorcak** [comment]
+1

**Comment by inferpse** [comment]
+1

**Comment by dhoko** [comment]
+1

```
Uncaught Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=app
REGEX_STRING_REGEXP 
@ vendor.min.js:68(anonymous function) 
@ vendor.min.js:1958ensure 
@ vendor.min.js:1882module 
@ vendor.min.js:1956createModule 
@ VM10901:174bootstrap 
@ VM10901:162(anonymous function) 
@ VM10901:270
```

**Comment by filso** [comment]
Yep, true story :)
Working on it

Thank you for feedback!

**Comment by filso** [comment]
0.2.5 with the fix is just being published in web store.

I found it impossible to patch `angular.bootstrap` asynchronously, so you'll have to enter the name of the app if you don't use `ng-app` tag

**Comment by himdel** [comment]
> you'll have to enter the name of the app if you don't use ng-app

@filso .. that's problematic, the app doesn't strictly need to have a name. ...(crickets)... However, looking at angular code, it seems that `angular.bootstrap` gives the bootstrapped app the name "ng". It may be worth exploring if this is consistent across versions and maybe the name could default to ng if so.

Also, don't get me wrong, I love that it doesn't crash anymore, but still.. :).

**Comment by filso** [comment]
@himdel I'm well aware of that, but there's nothing I can do about it. The problem is that your app might be bootstrapped with arbitrary long delay. I use a bunch of hacks to get the module data, but getting an actual app name is trickier.

The only way to determine app name automatically is by patching `angular.bootstrap` before your code invokes it. So it would have to do something like:

```<script src="angular.js"></script>
<!-- patch angular.bootstrap -->
<script src="your_app_with_angular_bootstrap.js"></script>```

But there's no way to do it with Chrome extension. And that would only work if you don't concatenate these scripts together.

**Comment by himdel** [comment]
Right you are. Well, it's nifty either way.

But actually, is there any way to *not* trigger a reload when you enter the app name? This may not be a typical use case I guess, but when you have an large app with only parts using angular... Well I load the angular part of the app, open the dependency graph, type in ng ... and it reloads the whole page leaving me in the non-angular part. And when I click to get to the angular part again, it's already loaded and I can only see ng, with no dependencies.

**Comment by filso** [comment]
@himdel so why don't you type your app name instead of 'ng'? then it will poll your page until it finds app with your name
