### ISSUE TITLE
Array.prototype.find shim is enumerable 

### ISSUE THREAD

**Issue by SomeKittens** [filso/ng-dependency-graph#3]
Whatever you're using to shim out `Array.prototype.find` is enumerable, meaning that:

```javascript
for (var x in myArr) {
  // "find" will be x here
}
```

Yes this is terrible practice (it's in a library we're using that I hope to pull out by the end of the year).  Still, shouldn't be enumerable.

**Comment by SchizoDuckie** [comment]
This is causing me multiple problems and has just lost me a day of work.

Somehow it's showing up when enumerating and serializing *some* objects, which leads to wrong assumptions and very unclear behavior.

Please fix this asap.
Disabling the extension for now.

**Comment by filso** [comment]
Ok 0.2.5 is just being published in web store. Apart from removing find shim I also added option of disabling graph per app. Sorry for the trouble, thank you for feedback!

**Comment by SchizoDuckie** [comment]
Excellent work :) Maybe it's even possible to just enable it per-app or even per session instead of running it by default? That would lighten the load and keep performance optimal when you're not browsing the graph (Which, frankly, you won't do as much as you will load the console)

**Comment by SomeKittens** [comment]
@filso Excellent!  Glad to have this back in action.

**Comment by filso** [comment]
@SchizoDuckie it is enabled per-app - if cookie isn't set, it won't run any code in inspected window other than related to app detection
