### ISSUE TITLE
add refresh graph button

### ISSUE THREAD

**Issue by chiptus** [filso/ng-dependency-graph#4]
To refresh the graph, it seems to me, you need to close the DevTools and refresh the page, only refreshing didn't work form

**Comment by chiptus** [comment]
Great extension!

**Comment by filso** [comment]
It should refresh automatically when you refresh the tab, so I guess it could be a bug.. does it happen on any live site for which it's happening?

Thank you

**Comment by filso** [comment]
That was a bug, sorry. :) it should refresh automatically now, fixed in 0.2.8
