### ISSUE TITLE
Custom app name.

### ISSUE THREAD

**Issue by SayusiAndo** [filso/ng-dependency-graph#6]
Hi,

It is a great tool! Thanks for creating it! I would like to request that it works with app name different than 'app'. My app named differently and I get the error message below. However, when I rename my app to app (I'll get a lot of error message due to broken module dependencies) but the graph is working.

"Uncaught Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."

**Comment by filso** [comment]
Hi Sayusi.
Thank you. Are you bootstraping your app manually? ie. with `angular.bootstrap(...)`? It should work for any app name as long as you use "ng-app" tag somewhere. I'll fix it for apps that are bootstraped manualy

**Comment by SayusiAndo** [comment]
No, I do not do any bootstrapping. I'll create a simple app and put it into a git repo in the a next a few days.

**Comment by filso** [comment]
Do you use 'ng-app' tag then somewhere?

**Comment by SayusiAndo** [comment]
I have this in my index.html:

Doesn't matter whether I use data-ng-app or ng-app

```html
<!DOCTYPE html>
<html lang="en" data-ng-app="dilib">
<head>
    <title>Digital Library</title>
    <meta charset="utf-8" />
```

my app.js file
```javascript
(function () {
    'use strict';

    angular.module('dilib', [
        // Angular modules
        'ngAnimate',
        'ngRoute',

        // Custom modules
        'dilib.layout',

        // 3rd Party Modules
        'LocalStorageModule',


    ])
```

**Comment by filso** [comment]
do you load `app.js` asynchronously after all files are loaded by any chance? Do you use any AMD, like RequireJS? I used a bit naive approach to load modules, releasing patch soon.

Thanks for feedback!

**Comment by SayusiAndo** [comment]
Thanks for dealing with this issue!
No, just angular. But, here is the current index.html file:

```html
<!DOCTYPE html>
<html lang="en" data-ng-app="dilib">
<head>
    <title>Digital Library</title>
    <meta charset="utf-8" />

    <!-- inject:css -->
    <!-- endinject -->

</head>
<body>

    <!-- inject:js -->
    <script src="scripts/jquery.js"></script>
    <script src="scripts/angular.js"></script>
    <script src="scripts/angular-sanitize.js"></script>
    <script src="scripts/angular-animate.js"></script>
    <script src="scripts/angular-route.js"></script>
    <script src="scripts/lodash.js"></script>
    <script src="scripts/restangular.js"></script>
    <script src="scripts/http-auth-interceptor.js"></script>
    <script src="scripts/q.js"></script>
    <script src="scripts/angular-local-storage.js"></script>
    <script src="dilibApp/dilib.js"></script>
    <script src="dilibApp/interceptors/authInterceptorFactory.js"></script>
    <script src="dilibApp/layout/dilib.layout.js"></script>
    <script src="dilibApp/layout/requestAuthorizationController.js"></script>
    <script src="dilibApp/layout/requestAuthorizationService.js"></script>
    <!-- endinject -->

    <div data-ng-include="'dilibApp/layout/layout.html'"></div>

</body>
</html>
```

**Comment by filso** [comment]
Woops... I forgot about `x-` and `data-` prefixes. If you want a quick fix, you can use `ng-app` instead of `data-ng-app` now, this will be fixed in next release 0.2.5.

**Comment by filso** [comment]
Ok 0.2.5 is just being published in web store. Hope it works well!

**Comment by SayusiAndo** [comment]
Nice, nice, and nice! Thanks for the fix! :)
